import { ExerciseDef } from '../../store/useWorkoutStore';

export const EXERCISE_DATABASE: ExerciseDef[] = [
  // BODYWEIGHT - CHEST / TRICEPS
  {
    id: 'pushup',
    name: 'Push-Up',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'diamond_pushup',
    name: 'Diamond Push-Up',
    muscleGroup: 'Triceps',
    secondaryMuscles: ['Chest'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'dips',
    name: 'Dips',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipmentRequired: ['Dip Bar'], // Or 'No Equipment' if using chairs, but keeping strict for now
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 90,
  },

  // BODYWEIGHT - BACK / BICEPS
  {
    id: 'pullup',
    name: 'Pull-Up',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps', 'Shoulders'],
    equipmentRequired: ['Pull-up Bar'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'chinup',
    name: 'Chin-Up',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipmentRequired: ['Pull-up Bar'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'bodyweight_row',
    name: 'Bodyweight Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipmentRequired: ['Pull-up Bar', 'Dip Bar'], // Requires something to hang from horizontally
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },

  // BODYWEIGHT - LEGS
  {
    id: 'bodyweight_squat',
    name: 'Bodyweight Squat',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Glutes', 'Core'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'lunges',
    name: 'Walking Lunges',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Glutes'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'jump_squat',
    name: 'Jump Squat',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Conditioning'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },

  // CORE
  {
    id: 'plank',
    name: 'Plank',
    muscleGroup: 'Core',
    secondaryMuscles: ['Shoulders'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'timed',
    defaultSets: 3,
    defaultReps: 0,
    defaultDuration: 45,
    defaultRest: 45,
  },
  {
    id: 'crunches',
    name: 'Crunches',
    muscleGroup: 'Core',
    secondaryMuscles: [],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 20,
    defaultRest: 45,
  },
  {
    id: 'hanging_leg_raises',
    name: 'Hanging Leg Raises',
    muscleGroup: 'Core',
    secondaryMuscles: ['Back'],
    equipmentRequired: ['Pull-up Bar'],
    difficulty: 'Advanced',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },

  // DUMBBELLS
  {
    id: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipmentRequired: ['Dumbbells', 'Bench'], // Ideally bench, but floor press is fallback
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 90,
  },
  {
    id: 'db_floor_press',
    name: 'Dumbbell Floor Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps'],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'db_row',
    name: 'Dumbbell Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    muscleGroup: 'Shoulders',
    secondaryMuscles: ['Triceps'],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'db_lateral_raise',
    name: 'Lateral Raises',
    muscleGroup: 'Shoulders',
    secondaryMuscles: [],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 45,
  },
  {
    id: 'db_bicep_curl',
    name: 'Dumbbell Bicep Curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: [],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'db_goblet_squat',
    name: 'Goblet Squat',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Core', 'Glutes'],
    equipmentRequired: ['Dumbbells'], // Can also be Kettlebell
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'db_rdl',
    name: 'Dumbbell RDL',
    muscleGroup: 'Glutes',
    secondaryMuscles: ['Legs', 'Core'],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },

  // BARBELL
  {
    id: 'bb_bench_press',
    name: 'Barbell Bench Press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipmentRequired: ['Barbell', 'Bench'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 120,
  },
  {
    id: 'bb_squat',
    name: 'Barbell Squat',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Glutes', 'Core'],
    equipmentRequired: ['Barbell'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 120,
  },
  {
    id: 'bb_deadlift',
    name: 'Deadlift',
    muscleGroup: 'Back',
    secondaryMuscles: ['Legs', 'Glutes', 'Core'],
    equipmentRequired: ['Barbell'],
    difficulty: 'Advanced',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 5,
    defaultRest: 120,
  },
  {
    id: 'bb_ohp',
    name: 'Overhead Press',
    muscleGroup: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Core'],
    equipmentRequired: ['Barbell'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 120,
  },
  {
    id: 'bb_row',
    name: 'Barbell Row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps', 'Core'],
    equipmentRequired: ['Barbell'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 90,
  },

  // CONDITIONING
  {
    id: 'burpees',
    name: 'Burpees',
    muscleGroup: 'Conditioning',
    secondaryMuscles: ['Full Body'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'mountain_climbers',
    name: 'Mountain Climbers',
    muscleGroup: 'Conditioning',
    secondaryMuscles: ['Core'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'timed',
    defaultSets: 3,
    defaultReps: 0,
    defaultDuration: 45,
    defaultRest: 45,
  }
];

export const getExerciseById = (id: string): ExerciseDef | undefined => {
  return EXERCISE_DATABASE.find(ex => ex.id === id);
};
