import type { ExerciseDef } from '../../store/useWorkoutStore';

export const EXERCISE_DATABASE: ExerciseDef[] = [
  // BODYWEIGHT - CHEST / TRICEPS
  {
    id: 'pushup',
    name: 'PUSH-UP',
    voiceName: 'Push-up',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'diamond_pushup',
    name: 'DIAMOND PUSH-UP',
    voiceName: 'Diamond push-up',
    muscleGroup: 'Triceps',
    secondaryMuscles: ['Chest'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'dips',
    name: 'DIPS',
    voiceName: 'Dips',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipmentRequired: ['Dip Bar'], 
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 90,
  },

  // BODYWEIGHT - BACK / BICEPS
  {
    id: 'pullup',
    name: 'PULL-UP',
    voiceName: 'Pull-up',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps', 'Shoulders'],
    equipmentRequired: ['Pull-up Bar'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'chinup',
    name: 'CHIN-UP',
    voiceName: 'Chin-up',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipmentRequired: ['Pull-up Bar'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 90,
  },
  {
    id: 'bodyweight_row',
    name: 'BW ROW',
    voiceName: 'Bodyweight row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipmentRequired: ['Pull-up Bar', 'Dip Bar'], 
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },

  // BODYWEIGHT - LEGS
  {
    id: 'bodyweight_squat',
    name: 'BW SQUAT',
    voiceName: 'Bodyweight squat',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Glutes', 'Core'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'lunges',
    name: 'LUNGES',
    voiceName: 'Walking lunges',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Glutes'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'jump_squat',
    name: 'JUMP SQUAT',
    voiceName: 'Jump squat',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Conditioning'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },

  // CORE
  {
    id: 'plank',
    name: 'PLANK',
    voiceName: 'Plank',
    muscleGroup: 'Core',
    secondaryMuscles: ['Shoulders'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'timed',
    defaultSets: 3,
    defaultReps: 0,
    defaultDuration: 45,
    defaultRest: 45,
  },
  {
    id: 'crunches',
    name: 'CRUNCHES',
    voiceName: 'Crunches',
    muscleGroup: 'Core',
    secondaryMuscles: [],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 20,
    defaultRest: 45,
  },
  {
    id: 'hanging_leg_raises',
    name: 'HANGING LEG RAISES',
    voiceName: 'Hanging leg raises',
    muscleGroup: 'Core',
    secondaryMuscles: ['Back'],
    equipmentRequired: ['Pull-up Bar'],
    difficulty: 'Advanced',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },

  // DUMBBELLS
  {
    id: 'db_bench_press',
    name: 'DB BENCH PRESS',
    voiceName: 'Dumbbell bench press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipmentRequired: ['Dumbbells', 'Bench'], 
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 90,
  },
  {
    id: 'db_floor_press',
    name: 'DB FLOOR PRESS',
    voiceName: 'Dumbbell floor press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps'],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'db_row',
    name: 'DB ROW',
    voiceName: 'Dumbbell row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps'],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'db_shoulder_press',
    name: 'DB SHOULDER PRESS',
    voiceName: 'Dumbbell shoulder press',
    muscleGroup: 'Shoulders',
    secondaryMuscles: ['Triceps'],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },
  {
    id: 'db_lateral_raise',
    name: 'DB LATERAL RAISE',
    voiceName: 'Dumbbell lateral raise',
    muscleGroup: 'Shoulders',
    secondaryMuscles: [],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 45,
  },
  {
    id: 'db_bicep_curl',
    name: 'DB CURL',
    voiceName: 'Dumbbell bicep curl',
    muscleGroup: 'Biceps',
    secondaryMuscles: [],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'db_goblet_squat',
    name: 'GOBLET SQUAT',
    voiceName: 'Goblet squat',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Core', 'Glutes'],
    equipmentRequired: ['Dumbbells'], 
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 12,
    defaultRest: 60,
  },
  {
    id: 'db_rdl',
    name: 'DB RDL',
    voiceName: 'Dumbbell Romanian deadlift',
    muscleGroup: 'Glutes',
    secondaryMuscles: ['Legs', 'Core'],
    equipmentRequired: ['Dumbbells'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 60,
  },

  // BARBELL
  {
    id: 'bb_bench_press',
    name: 'BB BENCH PRESS',
    voiceName: 'Barbell bench press',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Shoulders'],
    equipmentRequired: ['Barbell', 'Bench'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 120,
  },
  {
    id: 'bb_squat',
    name: 'BB SQUAT',
    voiceName: 'Barbell squat',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Glutes', 'Core'],
    equipmentRequired: ['Barbell'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 120,
  },
  {
    id: 'bb_deadlift',
    name: 'DEADLIFT',
    voiceName: 'Barbell deadlift',
    muscleGroup: 'Back',
    secondaryMuscles: ['Legs', 'Glutes', 'Core'],
    equipmentRequired: ['Barbell'],
    difficulty: 'Advanced',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 5,
    defaultRest: 120,
  },
  {
    id: 'bb_ohp',
    name: 'OVERHEAD PRESS',
    voiceName: 'Barbell overhead press',
    muscleGroup: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Core'],
    equipmentRequired: ['Barbell'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 8,
    defaultRest: 120,
  },
  {
    id: 'bb_row',
    name: 'BB ROW',
    voiceName: 'Barbell row',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps', 'Core'],
    equipmentRequired: ['Barbell'],
    difficulty: 'Intermediate',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 10,
    defaultRest: 90,
  },

  // CONDITIONING
  {
    id: 'burpees',
    name: 'BURPEES',
    voiceName: 'Burpees',
    muscleGroup: 'Conditioning',
    secondaryMuscles: ['Full Body'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'repetition',
    defaultSets: 3,
    defaultReps: 15,
    defaultRest: 60,
  },
  {
    id: 'mountain_climbers',
    name: 'MOUNTAIN CLIMBERS',
    voiceName: 'Mountain climbers',
    muscleGroup: 'Conditioning',
    secondaryMuscles: ['Core'],
    equipmentRequired: ['No Equipment'],
    difficulty: 'Beginner',
    movementType: 'timed',
    defaultSets: 3,
    defaultReps: 0,
    defaultDuration: 45,
    defaultRest: 45,
  }
];

export const getExerciseById = (id: string): ExerciseDef | undefined => {
  return EXERCISE_DATABASE.find(ex => ex.id === id);
};
